# Generated by Django 4.1 on 2022-09-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolstockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='nombreCiudad',
            new_name='nombre',
        ),
    ]
